---
- name: Ensure Pip is installed.
  package:
    name: "{{ pip_package }}"
    state: present

- name: >-
    Ensure setuptools are installed.
    see https://github.com/ansible/ansible/issues/47361
  package:
    name: python-setuptools
    state: present
    update_cache: true
  when: install_setuptools

- name: Ensure pip_install_packages are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: "{{ pip_executable }}"
  with_items: "{{ pip_install_packages }}"
